version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test:
    executor:
      name: win/default
      size: large
    steps:
    - checkout
    - run: dotnet build -c Release -p:SkipSonar=true
    - run: >-
        dotnet test
        -c Release
        -l "junit;MethodFormat=Full;FailureBodyFormat=Verbose;LogFilePath=/tmp/junit/{assembly}.xml"
    - store_test_results:
        path: /tmp/junit

workflows:
  main:
    jobs:
    - build-and-test
