on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.302'
    - run: dotnet build
    - run: dotnet test
    - name: NuGet publish
      run: |
        dotnet_args="-c Release -p:NoPackageAnalysis=true"
        if [[ ! "$GITHUB_REF" =~ ^refs/tags/* ]]; then
          git_sha=`echo "${{ github.sha }}" | cut -c1-11`
          publish_datetime=`TZ=UTC date +%Y%m%d%H%M%S`
          version_suffix=dev."$publish_datetime"+git.sha."$git_sha"
          dotnet_args="$dotnet_args --version-suffix $version_suffix"
        fi

        dotnet pack Libplanet.Explorer $dotnet_args

        if [[ "$NUGET_API_KEY" != "" ]]; then
          dotnet nuget push ./Libplanet.Explorer/bin/Release/Libplanet.Explorer.*.nupkg \
            --api-key "$NUGET_API_KEY" \
            --source https://api.nuget.org/v3/index.json
        fi
      if: github.event_name != 'pull_request' && success()
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
