on: pull_request
name: on pull request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - run: dotnet build
