on: pull_request
name: on pull request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.302'
    - run: dotnet build
    - run: dotnet test
